#!/bin/bash

# Read config file
. config/config.sh
# Get values
. data/configparser.sh

echo -e "\nUmvirt LFS Multilib configuration"
echo -e "---------------------------------"
echo
echo "Temporary directory: $LFS"
echo "Sources directory: $SRCROOT"
echo
