#!/bin/bash

. config.sh

echo "Packages dir: $SRCROOT"

mkdir log
rm log/*

for filename in scripts/*;
do
 [ -e "$filename" ] || continue
file=`basename $filename`
echo "Processing file: $file"
touch log/$file.start
cat $filename | bash 2>&1 | tee log/$file.log
touch log/$file.finish
#find files
find /opt -type f -newer log/$file.start \! -newer log/$file.finish >> log/$file.files
find /usr -type f -newer log/$file.start \! -newer log/$file.finish >> log/$file.files




done
